### ISSUE TITLE
fetch is not defined

### ISSUE THREAD

**Issue by isaac-art** [argentlabs/argent-starknet-recover#6]
When attempting to run cli on macos (arm64) 

steps:
`$ chmod +x cli-macos-arm64`
`$ ./cli-macos-arm64`

returns:

```bash
pkg/prelude/bootstrap.js:1876
      throw error;
      ^

ReferenceError: fetch is not defined
    at Object.<anonymous> (/snapshot/argent-starknet-recover/dist/fetchPolyfill.js:16:23)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1855:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snapshot/argent-starknet-recover/dist/index.js:17:1)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
 ```

**Comment by ceejeey** [comment]
Facing same issue

**Comment by UIZorrot** [comment]
you may use a lower version of nodejs like 18 to fix this issue
